In [1]:
import numpy as np

In [29]:
from random import randrange

class TicTacToe: 
    
    def __init__(self):
        self.grid = np.zeros((3, 3), dtype=int)
        self.board = self.grid.reshape(9,)
        self.force_log = False
        self.winner = -1
        self.last_player = -1
        self.n = 9
        class ActionSpace:
            def sample(self):
                return randrange(self.n)
        class Symbol:
            CROSS = 0,
            CIRCLE = 1
    
    def render(self):
        self.force_log = True
    
    def close(self):
        pass
    
    def start_game(self):
        self.winner = -1
        self.last_player = -1
        self.grid = np.zeros((3, 3), dtype=int)
        self.board = self.grid.reshape(9,)

    def step(self, action):
        if action < 0 or action > 8:
            raise IndexError(action)
        x, y = np.unravel_index(action, ticTac.grid.shape)
        self.play(x, y, self.symbol)
        
        
    def play(self, x, y, symbol):
        if x < 0 or y < 0 or x >= 3 or y >= 3:
            raise IndexError(x,y)
        if self.grid[x, y] != 0:
            raise IndexError("Already played")
        if symbol > 2:
            raise IndexError("Wrong symbol", symbol)
        if symbol == self.last_player:
            raise IndexError("Same player playing twice")
        self.grid[x, y] = symbol
        self.last_player = symbol
        if self.has_winner(symbol):
            print("Winner {} !".format(symbol))
            self.winner = symbol
    

    def has_winner(self, symbol):
        return (
            (self.board[6] == symbol and self.board[7] == symbol and self.board[8] == symbol) or # across the top
            (self.board[3] == symbol and self.board[4] == symbol and self.board[5] == symbol) or # across the middle
            (self.board[0] == symbol and self.board[1] == symbol and self.board[2] == symbol) or # across the bottom
            (self.board[6] == symbol and self.board[3] == symbol and self.board[0] == symbol) or # down the left side
            (self.board[7] == symbol and self.board[4] == symbol and self.board[1] == symbol) or # down the middle
            (self.board[8] == symbol and self.board[5] == symbol and self.board[2] == symbol) or # down the right side
            (self.board[6] == symbol and self.board[4] == symbol and self.board[2] == symbol) or # diag
            (self.board[8] == symbol and self.board[4] == symbol and self.board[0] == symbol)) # diagonal

    def isBoardFull(self):
        # Return True if every space on the board has been taken. Otherwise return False.
        for i in range(9):
            if self.board[i] == 0:
                return False
        if self.winner == -1:
            self.winner = 0
        return True

In [32]:
ticTac = TicTacToe()
ticTac.start_game()
i = 0
pion = 0
while ticTac.winner == -1:
    while ticTac.board[i] != 0:
        i = randrange(9)

    ticTac.symbol = pion % 2 + 1
    ticTac.step(i)
    pion += 1
    print(ticTac.grid, ticTac.board)

[[1 0 0]
 [0 0 0]
 [0 0 0]] [1 0 0 0 0 0 0 0 0]
[[1 0 0]
 [0 0 2]
 [0 0 0]] [1 0 0 0 0 2 0 0 0]
[[1 0 0]
 [1 0 2]
 [0 0 0]] [1 0 0 1 0 2 0 0 0]
[[1 0 0]
 [1 0 2]
 [2 0 0]] [1 0 0 1 0 2 2 0 0]
[[1 0 0]
 [1 0 2]
 [2 1 0]] [1 0 0 1 0 2 2 1 0]
[[1 2 0]
 [1 0 2]
 [2 1 0]] [1 2 0 1 0 2 2 1 0]
[[1 2 0]
 [1 1 2]
 [2 1 0]] [1 2 0 1 1 2 2 1 0]
[[1 2 2]
 [1 1 2]
 [2 1 0]] [1 2 2 1 1 2 2 1 0]
Winner 1 !
[[1 2 2]
 [1 1 2]
 [2 1 1]] [1 2 2 1 1 2 2 1 1]


In [18]:
idx = 2
unravel = np.unravel_index(idx, ticTac.grid.shape)
print(ticTac.board[idx], ticTac.grid[unravel])

1 1
